const express = require("express");
const router = express.Router();
const albumController = require("../controllers/albumController");
const artistController = require("../controllers/artistController");
const genreController = require("../controllers/genreController");
const songController = require("../controllers/songController");
router.get("/", albumController.index);
router.get("/albums", albumController.albumList);
router.get("/album/create", albumController.albumCreate);
router.post("/album/create", albumController.albumCreatePost);
router.get("/album/:id/update", albumController.albumUpdate);
router.post("/album/:id/update", albumController.albumUpdatePost);
router.get("/album/:id/delete", albumController.albumDelete);
router.post("/album/:id/delete", albumController.albumDeletePost);
router.get("/album/:id", albumController.albumDetail);
router.get("/artists", artistController.artistList);
router.get("/artist/create", artistController.artistCreate);
router.post("/artist/create", artistController.artistCreatePost);
router.get("/artist/:id/update", artistController.artistUpdate);
router.post("/artist/:id/update", artistController.artistUpdatePost);
router.get("/artist/:id/delete", artistController.artistDelete);
router.get("/artist/:id", artistController.artistDetail);
router.get("/genres", genreController.genreList);
router.get("/genre/create", genreController.genreCreate);
router.post("/genre/create", genreController.genreCreatePost);
router.get("/genre/:id/update", genreController.genreUpdate);
router.post("/genre/:id/update", genreController.genreUpdatePost);
router.get("/genre/:id/delete", genreController.genreDelete);
router.post("/genre/:id/delete", genreController.genreDeletePost);
router.get("/genre/:id", genreController.genreDetail);
router.get("/songs", songController.songList);
router.get("/song/create", songController.songForm);
router.post("/song/create", songController.songCreatePost);
router.get("/song/:id/delete", songController.songDelete);
router.post("/song/:id/delete", songController.songDeletePost);
router.get("/song/:id/update", songController.songUpdate);
router.post("/song/:id/update", songController.songUpdatePost);
router.get("/song/:id", songController.songDetail);

module.exports = router;
